export const COMPONENTS_ADD_MASTER_SPINNER_START = 'COMPONENTS_ADD_MASTER_SPINNER_START';
export const COMPONENTS_ADD_MASTER_SPINNER_STOP = 'COMPONENTS_ADD_MASTER_SPINNER_STOP';
export const COMPONENTS_ADD_MASTER_ACTION_SUCCESS = 'COMPONENTS_ADD_MASTER_ACTION_SUCCESS';
export const COMPONENTS_ADD_MASTER_ACTION_FAILED = 'COMPONENTS_ADD_MASTER_ACTION_FAILED';
export const COMPONENTS_ADD_MASTER_FORM = 'frmAddMaster';
