export const COMPONENTS_ADD_MASTER_LOAD_SUCCESS = 'COMPONENTS_ADD_MASTER_LOAD_SUCCESS';
export const COMPONENTS_ADD_MASTER_SPINNER_START = 'COMPONENTS_ADD_MASTER_SPINNER_START';
export const COMPONENTS_ADD_MASTER_SAVE = 'COMPONENTS_ADD_MASTER_SAVE';
