export const COMPONENTS_ADD_MASTER_SPINNER_START = 'COMPONENTS_ADD_MASTER_SPINNER_START';
export const COMPONENTS_ADD_MASTER_SPINNER_STOP = 'COMPONENTS_ADD_MASTER_SPINNER_STOP';
export const COMPONENTS_ADD_MASTER_SAVE = 'COMPONENTS_ADD_MASTER_SAVE';
